### PR TITLE
Bugfix/37/update sveltekit

### LINKED ISSUE #37: Update sveltekit
**Describe the bug**

A few Sveltekit/Vite updates:

- https://github.com/sveltejs/kit/discussions/5359
- https://github.com/sveltejs/kit/pull/5332
- https://github.com/sveltejs/kit/discussions/5748

Doesn't look like `svelte-paginate` works with this new version, so probably need to rewrite it

### PR DESCRIPTION
**Pull request by jochemvogel**
# Description

Closes #37

- [x] Fix (or rewrite) `svelte-paginate`. Currently not ready for the update

### CODE REVIEW

File: src/routes/+page.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
+import { error } from '@sveltejs/kit';
+import type { PageLoad } from './$types';
```
Comment (jochemvogel) [inline src/routes/+page.ts:3]: Put these imports in the right order (everywhere in the code // check every import)

File: src/routes/[category].json/+server.ts [hunk 2]
```diff
@@ -1,8 +1,10 @@
+// @TODO: Is RequestHandler the right type? Looks like a response => also check other pages
```
Comment (jochemvogel) [inline src/routes/[category].json/+server.ts]: Check if this is right

**Review by jochemvogel — COMMENTED** [review]
Added a few comments. Change them before merging

File: src/lib/components/method/MethodList.svelte [hunk 3]
```diff
@@ -1,7 +1,7 @@
 <script lang="ts">
 	import type { Method } from '$lib/types';
 
-	import { paginate, LightPaginationNav, DarkPaginationNav } from 'svelte-paginate';
+	// import { paginate, LightPaginationNav, DarkPaginationNav } from 'svelte-paginate';
```
Comment (jochemvogel) [inline src/lib/components/method/MethodList.svelte]: Fix `svelte-paginate`
